### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by andreac** [andylockran/heatmiserV3#7]
Hi, i'm trying to use heatmiserV3

when I test, I obtain this error in connection.hmserial. Thi is the code

`import json
from heatmiserV3 import heatmiser, connection

self.con = connection.hmserial('192.168.1.110', '8068')
self.con.open()
self.thermostat1 = heatmiser.HeatmiserThermostat(1, 'prt', self.con)
data = self.thermostat1.get_dcb()
print(json.dumps(data, indent=2))`

**Comment by andylockran** [comment]
Hey @andreac ,

I've done a fairly significant and easier to use rewrite.  Let me know a bit more about your setup.
